apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: gitops-1.20.3-stage-
  namespace: rh-openshift-gitops-tenant
spec:
  gracePeriodDays: 7
  releasePlan: gitops-1-20-stage
  snapshot: gitops-1-20-20260423-123725-000
  data:
    releaseNotes:
      type: RHBA
      cves: []
      