pull_request_rules:
  - name: auto-approve daily BUILD bump PRs
    conditions:
      - author=github-actions[bot]
      - files = BUILD
      - title ~= "^chore(build): bump to .*$"
      - or:
          - base=main
          - base ~= "^release-.*$"
      #- check-success ~= "^Red Hat Konflux"
    actions:
      review:
        type: APPROVE
        message: "Auto-approved daily BUILD bump PR."
      merge:
        method: squash
