# Release Metadata
release:
  name: OpenShift GitOps Operator
  version: "99.99.99"
  olm:
    # TODO: Compute olm data automatically
    name: "openshift-gitops-operator.v99.99.99"
    channel: "latest,gitops-99.99"
    replaces: "openshift-gitops-operator.v99.99.98"
    skip-range: "" # empty for z-stream & ">=1.0.0 <x.y.0" for y-stream
  konflux:
    repo: https://github.com/rh-gitops-midstream/release.git
    branch: main
    application: gitops-main
  managers:
    - name: "Siddhesh Ghadi"
      github: svghadi
      email: "sghadi@redhat.com"
# Source code repositories
# This section defines the source repositories for GitOps Operator artifacts built from source.
# See docs/sources.md for details on each field and usage instructions.
# On update, run `make sources` to update & validate the submodules.
# Note: `commit` is always used to perform the actual checkout. `ref` is purely metadata for CI which can be a tag or branch.
sources:
  - path: sources/gitops-operator
    url: https://github.com/redhat-developer/gitops-operator.git
    ref: master
    commit: facefc0bc143a90b8fec907c8d287793d99c2904
    auto-update: true
  - path: sources/argo-cd
    url: https://github.com/argoproj/argo-cd.git
    ref: master
    commit: c78cce03169b628f5c76eea9893bc80d4fc846c4
    auto-update: true
  - path: sources/argo-rollouts
    url: https://github.com/argoproj/argo-rollouts.git
    ref: v1.10.0-rc1
    commit: d1c296793cfd2dffc90fb89d919ee2bbf9b10ab5
    auto-update: true
  - path: sources/kustomize
    url: https://github.com/kubernetes-sigs/kustomize.git
    ref: kustomize/v5.8.1
    commit: 9790a1c3efd2fd35f1b768d495112834176581c1
    auto-update: true
  - path: sources/helm
    url: https://github.com/helm/helm.git
    ref: v3.19.5
    commit: 4a19a5b6fb912c5c28a779e73f2e0880d9e239a4
    auto-update: true
  - path: sources/dex
    url: https://github.com/rh-gitops-midstream/dex.git
    ref: v2.45.0
    commit: af68bd66272a6505de507fe52d441de7e5e881e4
    auto-update: true
  - path: sources/git-lfs
    url: https://github.com/git-lfs/git-lfs.git
    ref: v3.7.1
    commit: b84b33847fe6458f36ef521534dc0eac953cb379
    auto-update: true
  - path: sources/ssh-connect
    url: https://github.com/gotoh/ssh-connect.git
    ref: master
    commit: b65b09a0ee06950972233e8ea86ef87c4e63b3c9
    auto-update: true
  - path: sources/tini
    url: https://github.com/krallin/tini.git
    ref: master
    commit: 0b44d3665869e46ccbac7414241b8256d6234dc4
    auto-update: true
  - path: sources/argocd-extension-installer
    url: https://github.com/argoproj-labs/argocd-extension-installer.git
    ref: main
    commit: 44a5ab8e6998df0beb6f293b3607262db53aa8c7
    auto-update: true
  - path: sources/gitops-console-plugin
    url: https://github.com/redhat-developer/gitops-console-plugin.git
    ref: main
    commit: 3ea06fd60b5aeefd514988a108bc805c940687e7
    auto-update: true
  - path: sources/gitops-console-plugin-4-18
    url: https://github.com/redhat-developer/gitops-console-plugin.git
    ref: release-4.18
    commit: be9441150705d789652822d8fe9396f132dd4bf1
    auto-update: true
  - path: sources/gitops-backend
    url: https://github.com/redhat-developer/gitops-backend.git
    ref: master
    commit: 2c16e0c8eaa6923ac35d9256a36f13349e10d339
    auto-update: true
  - path: sources/rollouts-plugin-trafficrouter-openshift
    url: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift.git
    ref: main
    commit: 1495bbad184a05cde955fb21dcf35d05c3e58d98
    auto-update: true
  - path: sources/gitops-must-gather
    url: https://github.com/redhat-developer/gitops-must-gather.git
    ref: main
    commit: 2d10f1d873120c6ab95df99e262430f4ea05f7c5
    auto-update: true
  - path: sources/rollout-extension
    url: https://github.com/argoproj-labs/rollout-extension.git
    ref: master
    commit: 09102635500867f4119ae63008bf1fe1ae7328b5
    auto-update: true
  - path: sources/argocd-agent
    url: https://github.com/argoproj-labs/argocd-agent.git
    ref: main
    commit: 7bf329860e465e5138559fc1f6f79b7f7caba042
    auto-update: true
  - path: sources/argocd-image-updater
    url: https://github.com/argoproj-labs/argocd-image-updater.git
    ref: v1.3.0
    commit: 098b544f1c7d6d1368e89c3f8d92415ede353916
    auto-update: true
  - path: sources/gitops-promoter
    url: https://github.com/argoproj-labs/gitops-promoter.git
    ref: v0.35.0
    commit: cabfecc9ba28cffb0da2f32a7d5a93516ae059c1
    auto-update: true
# External images pulled directly from Red Hat registry and are
# required by the operator at runtime.
# Bundle generation script will automatically fetch latest sha for each image
# based on the version specified.
externalImages:
  - name: "haproxy"
    image: registry.redhat.io/openshift4/ose-haproxy-router-rhel9
    version: v4.19
  - name: "redis"
    image: registry.redhat.io/rhel9/redis-7
    version: latest
# Konflux images are images that are built from the source in this repository
konfluxImages:
  - name: argo-rollouts
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argo-rollouts-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/argo-rollouts-rhel9"
  - name: argocd-extenstions
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-extensions-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-extensions-rhel9"
  - name: argocd
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-rhel9"
  - name: argocd-agent
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agent-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-agent-rhel9"
  - name: argocd-image-updater
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-image-updater-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-image-updater-rhel9"
  - name: console-plugin
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/console-plugin-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/console-plugin-rhel9"
  - name: console-plugin-4-18
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/console-plugin-4-18-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/console-plugin-4-18-rhel9"
  - name: dex
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/dex-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/dex-rhel9"
  - name: gitops
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-rhel9"
  - name: gitops-operator-bundle
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle"
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-operator-bundle"
  - name: gitops-operator
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9-operator"
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-rhel9-operator"
  - name: must-gather
    buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/must-gather-rhel9"
    releaseRef: "registry.redhat.io/openshift-gitops-1/must-gather-rhel9"
