const fs = require("fs");

// Rewrite only the argo-ui git/tarball pin to sources/argo-ui-cd (same commit as the
// git dep in sources/argo-cd/ui). All other lockfile entries stay as in sources/argo-cd/ui.
//
// Regenerated by `make sources` via hack/pin-pnpm-deps.sh:
//   cp sources/argo-cd/ui/pnpm-lock.yaml containers/argocd/ui/pnpm-lock.yaml
//   node containers/argocd/ui/pin-argo-ui.js containers/argocd/ui/pnpm-lock.yaml

const GIT_SPEC_RE = /git\+https:\/\/github\.com\/argoproj\/argo-ui\.git#[0-9a-f]+/g;
const TARBALL_RE = /https:\/\/codeload\.github\.com\/argoproj\/argo-ui\/tar\.gz\/[0-9a-f]+/g;
const RESOLUTION_RE =
    /resolution: \{tarball: https:\/\/codeload\.github\.com\/argoproj\/argo-ui\/tar\.gz\/[0-9a-f]+\}/g;
const FILE_SPEC = "file:../../../sources/argo-ui-cd";
const FILE_RESOLUTION =
    "resolution: {directory: ../../../sources/argo-ui-cd, type: directory, tarball: file:../../../sources/argo-ui-cd}";

function pinPackageJson(file) {
    const pkg = JSON.parse(fs.readFileSync(file, "utf8"));
    if (!pkg.dependencies || !pkg.dependencies["argo-ui"]) {
        console.error(`${file} has no argo-ui dependency`);
        process.exit(1);
    }
    pkg.dependencies["argo-ui"] = FILE_SPEC;
    fs.writeFileSync(file, JSON.stringify(pkg, null, 4) + "\n");
}

function pinLockfile(file) {
    const original = fs.readFileSync(file, "utf8");
    if (!GIT_SPEC_RE.test(original) && !TARBALL_RE.test(original)) {
        GIT_SPEC_RE.lastIndex = 0;
        TARBALL_RE.lastIndex = 0;
        if (!original.includes(FILE_SPEC)) {
            console.error(`${file} has no argo-ui git/tarball reference to pin`);
            process.exit(1);
        }
        return;
    }
    GIT_SPEC_RE.lastIndex = 0;
    TARBALL_RE.lastIndex = 0;
    RESOLUTION_RE.lastIndex = 0;
    const pinned = original
        .replace(GIT_SPEC_RE, FILE_SPEC)
        .replace(RESOLUTION_RE, FILE_RESOLUTION)
        .replace(TARBALL_RE, FILE_SPEC);
    fs.writeFileSync(file, pinned);
}

const target = process.argv[2];
if (!target) {
    pinPackageJson("package.json");
    pinLockfile("pnpm-lock.yaml");
} else if (target.endsWith("pnpm-lock.yaml")) {
    pinLockfile(target);
} else {
    pinPackageJson(target);
}
