{{- if .Values.pullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-pull-secret" (include "openshift-gitops-operator.fullname" .)) .Values.pullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-gitops-operator.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.pullSecret.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | default "" | b64enc | quote }}
{{- end }}
