apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: openshift-gitops-operator-controller-manager
  labels:
    {{- include "openshift-gitops-operator.labels" . | nindent 4 }}
  name: openshift-gitops-operator-metrics-monitor-bearer-token
type: kubernetes.io/service-account-token
