{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    {{- include "openshift-gitops-operator.labels" . | nindent 4 }}
  name: {{ include "openshift-gitops-operator.serviceAccountName" . }}
{{- if .Values.pullSecret.create }}
imagePullSecrets:
  - name: {{ default (printf "%s-pull-secret" (include "openshift-gitops-operator.fullname" .)) .Values.pullSecret.name }}
{{- end }}
{{- end }}
