apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: gitops-1.18.6-prod-
  namespace: rh-openshift-gitops-tenant
spec:
  gracePeriodDays: 7
  releasePlan: gitops-1-18-prod
  snapshot: gitops-1-18-20260518-152634-000
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2026-33186
          component: dex-1-18
        - key: CVE-2026-33487
          component: dex-1-18
        - key: CVE-2026-34986
          component: dex-1-18
        - key: CVE-2026-32281
          component: dex-1-18
        - key: CVE-2026-4800
          component: console-plugin-1-18
        - key: CVE-2026-33186
          component: gitops-1-18

          