apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev=7fe636227b27bc37345b823d4dded6450d7f4b21
    build.appstudio.redhat.com/commit_sha: 7fe636227b27bc37345b823d4dded6450d7f4b21
    build.appstudio.redhat.com/pull_request_number: "798"
    build.appstudio.redhat.com/target_branch: release-1.20
    pac.test.appstudio.openshift.io/branch: release-1.20
    pac.test.appstudio.openshift.io/cancel-in-progress: "true"
    pac.test.appstudio.openshift.io/check-run-id: "68827275945"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-gvmypj
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "56531091"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-openshift-gitops-tenant/pipelinerun/gitops-operator-bundle-1-20-on-push-pxgq8
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: |-
      event == "push" && target_branch == "release-1.20" && (
        "containers/gitops-operator-bundle/***".pathChanged() ||
        ".tekton/gitops-operator-bundle-push.yaml".pathChanged()
      )
    pac.test.appstudio.openshift.io/original-prname: gitops-operator-bundle-1-20-on-push
    pac.test.appstudio.openshift.io/pull-request: "798"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/rh-gitops-midstream/release
    pac.test.appstudio.openshift.io/repository: dex-main
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: svghadi
    pac.test.appstudio.openshift.io/sha: 7fe636227b27bc37345b823d4dded6450d7f4b21
    pac.test.appstudio.openshift.io/sha-title: 'chore(bundle): latest bundle updates
      for v1.20.1-2 (#798)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/rh-gitops-midstream/release/commit/7fe636227b27bc37345b823d4dded6450d7f4b21
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-1.20
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/release
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: release
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-03-27T03:45:46Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'argocd-rhel9-1-20'
      is(are) not included in snapshot due to missing valid containerImage or git
      source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"conforma-gitops-1-20-gitops-1-20-20260327-034223-000":{"lastUpdateTime":"2026-03-27T03:46:11.448991182Z"},"enterprise-contract-gitops-1-20-gitops-1-20-20260327-034223-000":{"lastUpdateTime":"2026-03-27T03:46:05.070365668Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1774582943000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/release
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-gitops-1-20","status":"TestPassed","lastUpdateTime":"2026-03-27T03:46:05.070365668Z","details":"Integration
      test passed","startTime":"2026-03-27T03:45:46.754916639Z","completionTime":"2026-03-27T03:46:05.070365668Z","testPipelineRunName":"enterprise-contract-gitops-1-20-kw7th"},{"scenario":"conforma-gitops-1-20","status":"TestPassed","lastUpdateTime":"2026-03-27T03:46:11.448991182Z","details":"Integration
      test passed","startTime":"2026-03-27T03:45:46.72274794Z","completionTime":"2026-03-27T03:46:11.448991182Z","testPipelineRunName":"conforma-gitops-1-20-s576z"}]'
  creationTimestamp: "2026-03-27T03:45:46Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: gitops-1-20
    appstudio.openshift.io/build-pipelinerun: gitops-operator-bundle-1-20-on-push-pxgq8
    appstudio.openshift.io/component: gitops-operator-bundle-1-20
    pac.test.appstudio.openshift.io/cancel-in-progress: "true"
    pac.test.appstudio.openshift.io/check-run-id: "68827275945"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: gitops-operator-bundle-1-20-on-push
    pac.test.appstudio.openshift.io/pull-request: "798"
    pac.test.appstudio.openshift.io/repository: dex-main
    pac.test.appstudio.openshift.io/sha: 7fe636227b27bc37345b823d4dded6450d7f4b21
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: release
    test.appstudio.openshift.io/pipelinerunfinishtime: "1774583144"
    test.appstudio.openshift.io/type: component
  name: gitops-1-20-20260327-034223-000
  namespace: rh-openshift-gitops-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: gitops-1-20
    uid: 53cf91f3-c7fd-4909-85c6-01715b9dc4e7
  resourceVersion: "7954918507"
  uid: 51d38a1c-9214-4119-80fb-2372a49e5b42
spec:
  application: gitops-1-20
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-cli@sha256:8df51c890451c257b5adde40154a66d6deef5b049a3d5525a2d9bfa0ad6768ae
    name: argocd-cli-1-20
    source:
      git:
        dockerfileUrl: clis/argocd/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/console-plugin-rhel9@sha256:ed35dbc85e4ffbded7c5bb9c85e7e82030b6fa047fb11bd345bece8cd07431b1
    name: console-plugin-1-20
    source:
      git:
        dockerfileUrl: containers/console-plugin/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9@sha256:159416d9e28cf394a8bde9ba92634750c4ae6e46486f7714d055af468f8ad217
    name: gitops-1-20
    source:
      git:
        dockerfileUrl: containers/gitops/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/kubectl-argo-rollouts-cli@sha256:d42bfb00eef44dc3551ff0f207ccec8b13b442a5543f10bf511a136203951564
    name: kubectl-argo-rollouts-cli-1-20
    source:
      git:
        dockerfileUrl: clis/kubectl-argo-rollouts/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argo-rollouts-rhel9@sha256:8f0f7c8caebaffa4b2cd6f6d0f3e94fed93b2e34c35a229178dc4da6e6357d93
    name: argo-rollouts-1-20
    source:
      git:
        dockerfileUrl: containers/argo-rollouts/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/dex-rhel9@sha256:d61b160166501af7d7efced50d5dcf3766c1f68365b8432dae6b81a4d7fe097f
    name: dex-1-20
    source:
      git:
        dockerfileUrl: containers/dex/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9-operator@sha256:fd980bdf8227af7685025b9153005945252cd27798fae276e2775d895bc90ba6
    name: gitops-operator-1-20
    source:
      git:
        dockerfileUrl: containers/gitops-operator/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:f8301c386f55405c5933470d4034332b44559e59d4d99c2d70db0133551f9b73
    name: gitops-operator-bundle-1-20
    source:
      git:
        revision: 7fe636227b27bc37345b823d4dded6450d7f4b21
        url: https://github.com/rh-gitops-midstream/release
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-rhel9@sha256:90d01a4812e54dcb7920a115dfa623e2ee16c6100c113f06ac9b84c9d4780e8a
    name: argocd-1-20
    source:
      git:
        dockerfileUrl: containers/argocd/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-extensions-rhel9@sha256:659f31f3763a0358e6c0792edfef4b89c8ef5f73d0d233363de5235a866d9dd8
    name: argocd-extensions-1-20
    source:
      git:
        dockerfileUrl: containers/argocd-extensions/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/must-gather-rhel9@sha256:0f46a86e20590536cbf126aaf2ed4d56501310872445e8241899b17e5f288cea
    name: must-gather-1-20
    source:
      git:
        dockerfileUrl: containers/must-gather/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agent-rhel9@sha256:cdc6d6f86e08bded208cb772897e97455f11483c0a99a45d6548f19f3048a096
    name: argocd-agent-1-20
    source:
      git:
        dockerfileUrl: containers/argocd-agent/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-image-updater-rhel9@sha256:27e70552bc7d1c87dfe1bcb8cd358dad2dcacfcda258eaa5f74dae500d099160
    name: argocd-image-updater-1-20
    source:
      git:
        dockerfileUrl: containers/argocd-image-updater/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agentctl@sha256:1bba8978dcb5a518b08e50594c85f16d7a560bd36c0a9045b096f7656ea4c99a
    name: argocd-agentctl-1-20
    source:
      git:
        dockerfileUrl: clis/argocd-agentctl/Dockerfile
        revision: dc9a33d9efcaafe9f58b52d9e957ab622fb7e0fc
        url: https://github.com/rh-gitops-midstream/release.git
status:
  conditions:
  - lastTransitionTime: "2026-03-27T03:46:11Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-03-27T03:46:11Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-03-27T03:46:11Z"
    message: Skipping auto-release of the Snapshot because no ReleasePlans have the
      'auto-release' label set to 'true'
    reason: AutoReleased
    status: "True"
    type: AutoReleased
