apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: gitops-1.17.5-prod-
  namespace: rh-openshift-gitops-tenant
spec:
  gracePeriodDays: 7
  releasePlan: gitops-1-17-prod
  snapshot: gitops-1-17-20260225-105254-000
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2025-12816
          component: console-plugin-rhel8-1-17
        - key: CVE-2025-66418
          component: must-gather-rhel8-1-17
        - key: CVE-2025-13465
          component: console-plugin-rhel8-1-17
        - key: CVE-2025-61726
          component: argo-rollouts-rhel8-1-17
        - key: CVE-2025-61726
          component: argocd-agent-rhel8-1-17
        - key: CVE-2025-61726
          component: argocd-rhel8-1-17
        - key: CVE-2025-61726
          component: argocd-rhel9-1-17
        - key: CVE-2025-61726 
          component: dex-rhel8-1-17
        - key: CVE-2025-61726 
          component: gitops-rhel8-1-17
        - key: CVE-2025-61726
          component: gitops-rhel8-1-17
