# Default values for argocd-agent-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override Namespace to deploy your agent
namespaceOverride: ""

# Secret names for argo-agent deployment
tlsSecretName: "argocd-agent-client-tls"
userPasswordSecretName: "argocd-agent-agent-userpass"
image: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agent-rhel8"
imageTag: "sha256:d17069d475959a5fca31dc4cd2c2dce4f3d895f2c2b97906261791674a889079"   #this is picked form the release repo tag/branch

# config-map to config parameters for argocd-agent
agentMode: "autonomous"
auth: "mtls:any"
logLevel: "info"
server: "principal.server.address.com"
serverPort: "443"
metricsPort: "8181"
tlsClientInSecure: "false"
healthzPort: "8002"
redisAddress: "argocd-redis:6379"

tlsClientKeyPath: "/app/config/tls/tls.key"
tlsClientCertPath: "/app/config/tls/tls.crt"
tlsRootCAPath: "/app/config/tls/ca.crt"

networkPolicy:
  enabled: true 
  redis:
    enabled: true 
    name: allow-agent-to-redis
    namespace: "" 
    redisSelector:
      app.kubernetes.io/name: argocd-redis
    agentSelector:
      app.kubernetes.io/name: argocd-agent-agent