apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev=5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    build.appstudio.redhat.com/commit_sha: 5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    build.appstudio.redhat.com/pull_request_number: "1013"
    build.appstudio.redhat.com/target_branch: release-1.21
    pac.test.appstudio.openshift.io/branch: release-1.21
    pac.test.appstudio.openshift.io/cancel-in-progress: "true"
    pac.test.appstudio.openshift.io/check-run-id: "82048846912"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-yditwy
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "56531091"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-openshift-gitops-tenant/pipelinerun/gitops-operator-bundle-1-21-on-push-tvptq
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: |-
      event == "push" && target_branch == "release-1.21" && (
        "containers/gitops-operator-bundle/***".pathChanged() ||
        ".tekton/gitops-operator-bundle-push.yaml".pathChanged()
      )
    pac.test.appstudio.openshift.io/original-prname: gitops-operator-bundle-1-21-on-push
    pac.test.appstudio.openshift.io/pull-request: "1013"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/rh-gitops-midstream/release
    pac.test.appstudio.openshift.io/repository: dex-main
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: svghadi
    pac.test.appstudio.openshift.io/sha: 5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    pac.test.appstudio.openshift.io/sha-title: 'chore(bundle): latest bundle updates
      for v1.21.0-7 (#1013)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/rh-gitops-midstream/release/commit/5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-1.21
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/release
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: release
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-06-18T03:31:44Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"conforma-gitops-1-21-gitops-1-21-20260618-032544-000":{"lastUpdateTime":"2026-06-18T03:32:25.519222832Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1781753144000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/result-chains-git-commit: 5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/rh-gitops-midstream/release
    test.appstudio.openshift.io/result-image-digest: sha256:fc5565b546154b179739109ab730b1caf4e8d57632d1090720d08dae602fbee5
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle:5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    test.appstudio.openshift.io/source-repo-url: https://github.com/rh-gitops-midstream/release
    test.appstudio.openshift.io/status: '[{"scenario":"conforma-gitops-1-21","status":"BuildPLRInProgress","lastUpdateTime":"2026-06-18T03:32:25.519222832Z","details":"Integration
      test passed with warnings","startTime":"2026-06-18T03:31:45.071736811Z","completionTime":"2026-06-18T03:32:25.519222832Z","testPipelineRunName":"conforma-gitops-1-21-qtmlr"}]'
  creationTimestamp: "2026-06-18T03:31:44Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: gitops-1-21
    appstudio.openshift.io/build-pipelinerun: gitops-operator-bundle-1-21-on-push-tvptq
    appstudio.openshift.io/component: gitops-operator-bundle-1-21
    pac.test.appstudio.openshift.io/cancel-in-progress: "true"
    pac.test.appstudio.openshift.io/check-run-id: "82048846912"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: gitops-operator-bundle-1-21-on-push
    pac.test.appstudio.openshift.io/pull-request: "1013"
    pac.test.appstudio.openshift.io/repository: dex-main
    pac.test.appstudio.openshift.io/sha: 5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: rh-gitops-midstream
    pac.test.appstudio.openshift.io/url-repository: release
    test.appstudio.openshift.io/pipelinerunfinishtime: "1781753501"
    test.appstudio.openshift.io/type: component
  name: gitops-1-21-0-build-7
  namespace: rh-openshift-gitops-tenant
  resourceVersion: "9381884555"
  uid: cdb6cbb6-f5ca-472d-bf09-be144b5612ca
spec:
  application: gitops-1-21
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:fc5565b546154b179739109ab730b1caf4e8d57632d1090720d08dae602fbee5
    name: gitops-operator-bundle-1-21
    source:
      git:
        revision: 5af663c3a6111c380b0f8dffa1fd7eff163c5a2a
        url: https://github.com/rh-gitops-midstream/release
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/kubectl-argo-rollouts-cli@sha256:049e4e81f33997f5f9b1957eb64b3e0bf20de8a07e1ae0f892377679a3c8f6f4
    name: kubectl-argo-rollouts-cli-1-21
    source:
      git:
        dockerfileUrl: clis/kubectl-argo-rollouts/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/must-gather-rhel9@sha256:9b013075353fa46734035267f830f01581fad4b5a337b2490197b70e1c963448
    name: must-gather-1-21
    source:
      git:
        dockerfileUrl: containers/must-gather/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argo-rollouts-rhel9@sha256:887cc49617f87decc0dc6ba595739194fce6e95d849657723fcf227893a8a842
    name: argo-rollouts-1-21
    source:
      git:
        dockerfileUrl: containers/argo-rollouts/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-rhel9@sha256:1df65c944adf38f5b22f86f633a36d7e6d81f9bc744691ec4fc181bb076f96a8
    name: argocd-1-21
    source:
      git:
        dockerfileUrl: containers/argocd/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agent-rhel9@sha256:aa21554e99267be91fb17f093afc277615098060cd4cab6fd5d473a4ee46ef39
    name: argocd-agent-1-21
    source:
      git:
        dockerfileUrl: containers/argocd-agent/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agentctl@sha256:6560c9b1dd3fa01612b2dbe4a88dac2c6c675256abdbd1db4c7269f346608cee
    name: argocd-agentctl-1-21
    source:
      git:
        dockerfileUrl: clis/argocd-agentctl/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-cli@sha256:2676dfe1cb2b4de84050d2336068f9de9bbf2779d74c93f9a3f6572ffc2da25c
    name: argocd-cli-1-21
    source:
      git:
        dockerfileUrl: clis/argocd/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/dex-rhel9@sha256:a5ba068c793188f2300c3ffa40f53b9915f19a4cf517f5243be8918e61cf37ce
    name: dex-1-21
    source:
      git:
        dockerfileUrl: containers/dex/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-extensions-rhel9@sha256:812ebcdda9380161c64be9182b42fd9167f63da220f2e2f1adc4f6c00696a2eb
    name: argocd-extensions-1-21
    source:
      git:
        dockerfileUrl: containers/argocd-extensions/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-image-updater-rhel9@sha256:0d23ad519706b18f28100a309dd3b23fefbba10625905fb0b9f638add2c02cb9
    name: argocd-image-updater-1-21
    source:
      git:
        dockerfileUrl: containers/argocd-image-updater/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/console-plugin-rhel9@sha256:c1b7cb1c31f7f8987768e155df210ff89be20f5230355ec744aa75253dd73a2a
    name: console-plugin-1-21
    source:
      git:
        dockerfileUrl: containers/console-plugin/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9@sha256:36c5430f08f788b425c2b30dd6e7ceef3ae8162a4cb854b7dd459f4d91286295
    name: gitops-1-21
    source:
      git:
        dockerfileUrl: containers/gitops/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
  - containerImage: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9-operator@sha256:52db2c50a554a80b3560ece381cffcad41ceff7f34cd9c590b4f95a60f227c68
    name: gitops-operator-1-21
    source:
      git:
        dockerfileUrl: containers/gitops-operator/Dockerfile
        revision: 92e3f0dcd0c861d9eee67f7e18a80a2c2a9b059b
        url: https://github.com/rh-gitops-midstream/release.git
status:
  conditions:
  - lastTransitionTime: "2026-06-18T03:32:25Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-06-18T03:32:25Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-06-18T03:32:25Z"
    message: Skipping auto-release of the Snapshot because no ReleasePlans have the
      'auto-release' label set to 'true'
    reason: AutoReleased
    status: "True"
    type: AutoReleased
