apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" &&
      target_branch == "release-1.15" &&
      (
        "sources/argo-cd".pathChanged() ||
        "sources/git-lfs".pathChanged() ||
        "sources/helm".pathChanged() ||
        "sources/kustomize".pathChanged() ||
        "sources/ssh-connect".pathChanged() ||
        "sources/tini".pathChanged() ||
        "containers/argocd/***".pathChanged() ||
        ".tekton/argocd-push.yaml".pathChanged() ||
        "prefetch/rpms/ubi8/***".pathChanged() ||
        "BUILD".pathChanged() ||
        ".tekton/build-multi-platform-image.yaml".pathChanged() ||
        ".tekton/tasks/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-1-15
    appstudio.openshift.io/component: argocd-1-15
    pipelines.appstudio.openshift.io/type: build
  name: argocd-1-15-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-rhel8:{{revision}}
  - name: additional-tags
    value:
      - '{{target_branch}}'
  - name: dockerfile
    value: containers/argocd/Dockerfile
  - name: prefetch-input
    value: '[{"type":"gomod","path":"./sources/argo-cd"}, {"type":"yarn","path":"./sources/argo-cd/ui"}, {"type":"gomod","path":"./sources/kustomize/kustomize"}, {"type":"gomod","path":"./sources/helm"}, {"type":"gomod","path":"./sources/git-lfs"}, {"type":"rpm","path":"prefetch/rpms/ubi8"}, {"type":"npm","path":"prefetch/yarn"}]'
  - name: git-metadata-directories
    value:
      - sources/argo-cd
      - sources/git-lfs
      - sources/helm
      - sources/kustomize
      - sources/ssh-connect
      - sources/tini
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate: 
    serviceAccountName: build-pipeline-argocd-1-15
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}