apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" &&
      target_branch == "main" &&
      (
        "sources/argo-cd".pathChanged() ||
        "clis/argocd/***".pathChanged() ||
        ".tekton/argocd-cli-push.yaml".pathChanged() ||
        "BUILD".pathChanged() ||
        ".tekton/build-multi-platform-image.yaml".pathChanged() ||
        ".tekton/tasks/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-main
    appstudio.openshift.io/component: argocd-cli-main
    pipelines.appstudio.openshift.io/type: build
  name: argocd-cli-main-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-cli:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: additional-tags
    value:
    - '{{target_branch}}'
  - name: dockerfile
    value: clis/argocd/Dockerfile
  - name: prefetch-input
    value: '[{"type":"gomod","path":"./sources/argo-cd"}]'
  - name: git-metadata-directories
    value:
    - sources/argo-cd
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate:
    serviceAccountName: build-pipeline-argocd-cli-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}