apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >
      event == "push" && target_branch == "main" && ( "sources/argocd-extension-installer".pathChanged() || "sources/rollout-extension".pathChanged() || "containers/argocd-extensions/***".pathChanged() || ".tekton/argocd-extensions-push.yaml".pathChanged() || ".tekton/build-multi-platform-image.yaml".pathChanged() || ".tekton/tasks/***".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-main
    appstudio.openshift.io/component: argocd-extensions-main
    pipelines.appstudio.openshift.io/type: build
  name: argocd-extensions-main-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-extensions-rhel8:{{revision}}
  - name: additional-tags
    value:
      - '{{target_branch}}'
  - name: dockerfile
    value: containers/argocd-extensions/Dockerfile
  - name: prefetch-input
    value: '[{"type": "rpm", "path": "prefetch/rpms/ubi8"}]'
  - name: git-metadata-directories
    value:
      - sources/argocd-extension-installer
      - sources/rollout-extension
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate: 
    serviceAccountName: build-pipeline-argocd-extensions-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}