apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" &&
      target_branch == "main" &&
      (
        "sources/argocd-agent".pathChanged() ||
        "clis/argocd-agentctl/***".pathChanged() ||
        ".tekton/argocd-agentctl-cli-push.yaml".pathChanged() ||
        "BUILD".pathChanged() ||
        ".tekton/build-multi-platform-image.yaml".pathChanged() ||
        ".tekton/tasks/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-main
    appstudio.openshift.io/component: argocd-agentctl-main
    pipelines.appstudio.openshift.io/type: build
  name: argocd-agentctl-main-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-agentctl-{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: additional-tags
    value:
      - '{{target_branch}}'
  - name: dockerfile
    value: clis/argocd-agentctl/Dockerfile
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./sources/argocd-agent"}]'
  - name: git-metadata-directories
    value:
      - sources/argocd-agent
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate: 
    serviceAccountName: build-pipeline-argocd-agentctl-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}