apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" &&
      target_branch == "main" &&
      (
        "sources/gitops-operator".pathChanged() ||
        "containers/gitops-operator/***".pathChanged() ||
        ".tekton/gitops-operator-pull-request.yaml".pathChanged() ||
        ".tekton/build-multi-platform-image.yaml".pathChanged() ||
        ".tekton/tasks/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-main
    appstudio.openshift.io/component: gitops-operator-main
    pipelines.appstudio.openshift.io/type: build
  name: gitops-operator-main-on-pull-request
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-rhel9-operator:on-pr-{{pull_request_number}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
  - name: dockerfile
    value: containers/gitops-operator/Dockerfile
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./sources/gitops-operator"}]'
  - name: git-metadata-directories
    value:
      - sources/gitops-operator
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate: 
    serviceAccountName: build-pipeline-gitops-operator-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}