apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-1.16" && ( "sources/gitops-backend/***".pathChanged() || gitops-backend/***".pathChanged() || ".tekton/gitops-backend-*.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-1-16
    appstudio.openshift.io/component: gitops-backend-1-16
    pipelines.appstudio.openshift.io/type: build
  name: gitops-backend-1-16-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-backend:{{revision}}
  - name: dockerfile
    value: gitops-backend/Dockerfile
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
  - name: additional-tags
    value:
      - '{{target_branch}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./sources/gitops-backend"}]'
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/rh-gitops-midstream/release.git
      - name: revision
        value: '{{target_branch}}'
      - name: pathInRepo
        value: /konflux-ci/pipelines/build-multi-platform-image.yaml
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}