apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" &&
      target_branch == "release-1.17" &&
      (
        "containers/gitops-operator-bundle/***".pathChanged() ||
        ".tekton/gitops-operator-bundle-push.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitops-1-17
    appstudio.openshift.io/component: gitops-operator-bundle-1-17
    pipelines.appstudio.openshift.io/type: build
  name: gitops-operator-bundle-1-17-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle:{{revision}}
  - name: dockerfile
    value: containers/gitops-operator-bundle/Dockerfile
  - name: build-platforms
    value:
      - linux/x86_64
  - name: build-image-index
    value: "false"
  - name: additional-tags
    value:
      - '{{target_branch}}'
  - name: git-metadata-directories
    value:
      - sources/gitops-operator
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate: 
    serviceAccountName: build-pipeline-gitops-operator-bundle-1-17
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}