apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-gitops-midstream/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "gitops-operator-bundle/***".pathChanged() || ".tekton/gitops-operator-bundle-main-*.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-gitops-operator-main
    appstudio.openshift.io/component: gitops-operator-bundle-main
    pipelines.appstudio.openshift.io/type: build
  name: gitops-operator-bundle-main-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle-main:{{revision}}
  - name: dockerfile
    value: bundle.Dockerfile
  - name: path-context
    value: gitops-operator-bundle
  - name: build-image-index
    value: "false"
  - name: additional-tags
    value:
      - '{{target_branch}}'
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/rh-gitops-midstream/release.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /konflux-ci/pipelines/build-multi-platform-image.yaml
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
