apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: install-gitops-operator-subscription
spec:
  params:
    - name: bundleImage
      type: string
    - name: namespace
      type: string
      default: "openshift-gitops-operator"
    - name: installTimeout
      type: string
      default: "30m"
    - name: credentials
      type: string
      description: A volume to which the remote cluster credentials will be written.
    - name: kubeconfig
      type: string
      description: A path to the kubeconfig in the credentials volume
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
  env:
    - name: CATALOG_IMAGE
      value: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/catalog:v4.14"
    - name: NAMESPACE
      value: $(params.namespace)
    - name: INSTALL_TIMEOUT
      value: $(params.installTimeout)
    - name: KUBECONFIG
      value: "/credentials/$(params.kubeconfig)"
  image: registry.redhat.io/openshift4/ose-cli:latest
  script: |
    #!/bin/bash
    set -ex

    # 1. Ensure the namespace exists
    oc create namespace ${NAMESPACE} --dry-run=client -o yaml | oc apply -f -

    # 2. Create CatalogSource
    cat <<EOF | oc apply -f -
    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: gitops-stage
      namespace: openshift-marketplace
    spec:
      sourceType: grpc
      image: ${CATALOG_IMAGE}
      displayName: GitOps Stage Catalog
      publisher: Konflux
      updateStrategy:
        registryPoll:
          interval: 30m
    EOF

    # 3. Create OperatorGroup
    cat <<EOF | oc apply -f -
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: gitops-operator-group
      namespace: ${NAMESPACE}
    spec:
      targetNamespaces:
      - ${NAMESPACE}
    EOF

    # 4. Create Subscription
    cat <<EOF | oc apply -f -
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: openshift-gitops-operator
      namespace: ${NAMESPACE}
    spec:
      channel: latest
      name: openshift-gitops-operator
      source: gitops-stage
      sourceNamespace: openshift-marketplace
    EOF

    # 5. Wait for installation
    echo "Waiting for ClusterServiceVersion to appear and succeed..."
    # Give OLM a moment to generate the InstallPlan
    sleep 30 
    
    CSV_NAME=""
    for i in {1..30}; do
      CSV_NAME=$(oc get sub openshift-gitops-operator -n ${NAMESPACE} -o jsonpath='{.status.installedCSV}' || true)
      if [ -n "$CSV_NAME" ]; then break; fi
      echo "Waiting for subscription status to be updated..."
      sleep 10
    done

    if [ -z "$CSV_NAME" ]; then
      echo "Error: CSV name not found in subscription"
      oc get sub openshift-gitops-operator -n ${NAMESPACE} -o yaml
      exit 1
    fi

    oc wait --for=jsonpath='{.status.phase}'=Succeeded csv/${CSV_NAME} -n ${NAMESPACE} --timeout=10m
