apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: prepare-logs-for-oci-push
spec:
  params:
    - name: pipeline-run-name
      type: string
      description: Name of the PipelineRun whose logs should be collected.
    - name: namespace
      type: string
      description: Namespace where the PipelineRun was executed.
    - name: log-workspace
      type: string
  results:
    - name: LOG_ARTIFACT_TAG
      description: The tag generated for the log artifact.
  image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
  workingDir: /var/log-workspace
  volumeMounts:
    - name: "$(params.log-workspace)"
      mountPath: /var/log-workspace
  env:
    - name: PR_NAME
      value: "$(params.pipeline-run-name)"
    - name: PR_NAMESPACE
      value: "$(params.namespace)"
  script: |
    #!/bin/bash
    set -euo pipefail

    LOG_FILENAME="all-logs.txt"
    ARCHIVE_FILENAME="logs.tar.gz"

    IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"

    CMD="kubectl"

    ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read -r taskrun; do
        POD_NAME=$(${CMD} get tr "${taskrun}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.podName // empty')

        if [ -n "$POD_NAME" ]; then
            echo "--- LOGS FOR ${taskrun} (Pod: ${POD_NAME}) ---" >> "${LOG_FILENAME}" 2>&1
            ${CMD} logs --namespace "${PR_NAMESPACE}" pod/"${POD_NAME}" >> "${LOG_FILENAME}" 2>&1 || true
        fi
    done

    if [ -s "${LOG_FILENAME}" ]; then
        tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
        echo -n "${IMAGE_TAG}" > "$(step.results.LOG_ARTIFACT_TAG.path)"
    else
        echo -n "" > "$(step.results.LOG_ARTIFACT_TAG.path)"
        echo "No logs found, skipping archive."
    fi