name: Update microshift-gitops.spec File and Create PR

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      gitops_version:
        description: 'ArgoCD version suffix'
        required: true
        default: '1.17.0-5'
      gitops_registry:
        description: 'ArgoCD container registry'
        required: true
        default: 'registry.redhat.io'
      gitops_image_name:
        description: 'ArgoCD image name'
        required: true
        default: 'openshift-gitops-1/argocd-rhel9'
      redis_registry:
        description: 'Redis container registry'
        required: true
        default: 'registry.redhat.io'
      redis_image_name:
        description: 'Redis image name'
        required: true
        default: 'rhel9/redis-7'
      redis_tag_prefix:
        description: 'Redis tag prefix to search for'
        required: true
        default: '9.6-1755009825'
      gitops_release:
        description: 'Gitops Spec Release (??= version)'
        required: true
        default: '1.17.0'
      target_branch:
        description: 'The branch to create the pull request against'
        required: true
        default: 'GITOPS-6959_rpm_microshift-gitops_folder'

jobs:
  update-spec-and-create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo podman
    
    - name: Log in to registry.redhat.io
      run: |
        mkdir -p ~/.config/containers
        podman login registry.redhat.io -u ${{ secrets.RH_USERNAME }} -p ${{ secrets.RH_PASSWORD }}
    
    - name: Run the Pre-Build Script
      id: run_script
      working-directory: ./rpms/microshift-gitops
      env:
        GITOPS_VERSION: ${{ inputs.gitops_version }}
        GITOPS_REGISTRY: ${{ inputs.gitops_registry }}
        GITOPS_IMAGE_NAME: ${{ inputs.gitops_image_name }}
        REDIS_REGISTRY: ${{ inputs.redis_registry }}
        REDIS_IMAGE_NAME: ${{ inputs.redis_image_name }}
        REDIS_TAG_PREFIX: ${{ inputs.redis_tag_prefix }}
        GITOPS_RELEASE: ${{ inputs.gitops_release }}
        CI_ARGO_CD_UPSTREAM_TAG: ${{ inputs.ci_argo_cd_upstream_tag }}
      run: ./generate-spec-file.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: Update container image digests and versions"
        branch: "bot/update-spec-${{ github.run_id }}"
        delete-branch: true
        title: "Automated `${{ inputs.gitops_version }}` Spec File Update for ArgoCD & Redis "
        body: |
          This PR was automatically generated by the 'Update Spec File' GitHub Action.
          
          It updates the container image digests and versions based on the following inputs:
          - **Gitops Version**: `${{ inputs.gitops_version }}`
          - **Redis Tag Prefix**: `${{ inputs.redis_tag_prefix }}`
          - **ArgoCD Upstream Tag**: `${{ inputs.ci_argo_cd_upstream_tag }}`
          
          Automatically generated for `${{ inputs.TARGET_BRANCH }}` using GitHub Actions..
        #labels: |
        #  release-candidate
        base: ${{ inputs.target_branch }}
