name: Generate rpm microshift-gitops.spec file

on:
  workflow_dispatch:
    inputs:
      gitops_release:
        description: 'GitOps Spec Release version (e.g., 1.17.0)'
        required: true
        default: '1.17.0'
      konflux_argocd_image_name:
        description: 'The Konflux ArgoCD image name to use(e.g., argocd, argocd-rhel9)'
        required: true
        default: 'argocd-rhel9'
      argo_cd_image_sha_x86:
        description: 'The SHA256 digest for the Argo CD x86_64 image'
        required: true
        default: 'sha256:5f35a4ed723fa364bd58bc56a9491915ec8bed256a056b07429e1957580b1c4f'
      argo_cd_image_sha_arm:
        description: 'The SHA256 digest for the Argo CD arm64 image'
        required: true
        default: 'sha256:8168018c4ffadcda01fea61ec2bf005b556a28966dfdf60cf922a37392bcc987'
      redis_image_sha_x86:
        description: 'The SHA256 digest for the Redis x86_64 image'
        required: true
        default: 'sha256:300c0fd54f8f49eba19e6a16745fa7e225f1f66b571c8e02cd098ef45e03d1c8'
      redis_image_sha_arm:
        description: 'The SHA256 digest for the Redis arm64 image'
        required: true
        default: 'sha256:c796538bad7613deb1fba2bb76e736a6376b25ab97b2f944e67af00e01f5d965'
      target_branch:
        description: 'The branch to create the pull request against'
        required: true
        default: 'main'

jobs:
  update-spec-and-create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Run the Spec File Generation Script
      id: run_script
      working-directory: ./rpms/microshift-gitops
      env:
        GITOPS_VERSION: ${{ inputs.gitops_version }}
        GITOPS_RELEASE: ${{ inputs.gitops_release }}
        KONFLUX_ARGOCD_IMAGE_NAME: ${{ inputs.konflux_argocd_image_name }}
        ARGO_CD_IMAGE_SHA_X86: ${{ inputs.argo_cd_image_sha_x86 }}
        ARGO_CD_IMAGE_SHA_ARM: ${{ inputs.argo_cd_image_sha_arm }}
        REDIS_IMAGE_SHA_X86: ${{ inputs.redis_image_sha_x86 }}
        REDIS_IMAGE_SHA_ARM: ${{ inputs.redis_image_sha_arm }}
      run: ./generate-microshift-gitops-spec.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: Update container image digests for branch ${{ inputs.gitops_release }}"
        branch: "bot/update-spec-${{ github.run_id }}"
        delete-branch: true
        title: "Automated Spec File generated for GitOps ${{ inputs.gitops_release }}"
        body: |
          This PR was automatically generated by the 'Update Spec File' GitHub Action.
          
          It updates the container image digests based on the following inputs:
          - **GitOps release**: `${{ inputs.gitops_release }}`
          - **ArgoCD Image Name**: `${{ inputs.konflux_argocd_image_name }}`
          - **ArgoCD x86 SHA**: `${{ inputs.argo_cd_image_sha_x86 }}`
          - **ArgoCD ARM SHA**: `${{ inputs.argo_cd_image_sha_arm }}`
          - **Redis x86 SHA**: `${{ inputs.redis_image_sha_x86 }}`
          - **Redis ARM SHA**: `${{ inputs.redis_image_sha_arm }}`
          
          This update is for the `${{ inputs.target_branch }}` branch.
        base: ${{ inputs.target_branch }}